name: Tests

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5  # последняя версия

      - name: Check if the repository is private
        run: |
          if ${{ github.event.repository.private }}; then
            echo "Repository is private, skipping tests."
            exit 0
          fi
        shell: bash

      # - name: Tests
      #   uses: Yandex-Practicum/test-project-action@v1
      #   with:
      #     project: 'ono-tebe-nado'

      - name: Run tests manually
        run: |
          npm install
          npm test

